import React from "react";
import { auth } from "@/auth";
import Providers from "@/components/layout/providers";
import { Toaster } from "@/components/ui/sonner";

import { Lato } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en" className={`${lato.className}`}>
      <body className={"overflow-hidden"} suppressHydrationWarning={true}>
        <NextTopLoader showSpinner={false} />
        <Providers session={session}>
          <Toaster />
          {children}
        </Providers>
      </body>
    </html>
  );
}
